services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: trilha_net_api
    ports:
      - "1433:1433"
